// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvzdfkynzbjbsxizvdit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2emRma3luemJqYnN4aXp2ZGl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTczOTQsImV4cCI6MjA2MDU3MzM5NH0.xuvZ7psHGVvZjQaduSkIiedLvadZ2o2QVF_icZFtWdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);